<?php
/**
 *  Copyright 2015 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
namespace PetStore\V1000\Services;

use PetStore\V1000\Models\Pet;
use PetStore\V1000\Apis\PetApi;
    
/**
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 */
class PetService implements PetApi {
    /**
     * Update an existing pet
     */
    public function updatePet(Pet $body) {
    }

    /**
     * Add a new pet to the store
     */
    public function addPet(Pet $body) {
    }

    /**
     * Finds Pets by status
     */
    public function findPetsByStatus($status) {
    }

    /**
     * Finds Pets by tags
     */
    public function findPetsByTags($tags) {
    }

    /**
     * Find pet by ID
     */
    public function getPetById($pet_id) {
    }

    /**
     * Updates a pet in the store with form data
     */
    public function updatePetWithForm($pet_id, $name, $status) {
    }

    /**
     * Deletes a pet
     */
    public function deletePet($api_key, $pet_id) {
    }

    /**
     * uploads an image
     */
    public function uploadFile($pet_id, $additional_metadata, $file) {
    }
}
