<?php
/**
 *  Copyright 2015 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
namespace PetStore\V1000\Services;

use PetStore\V1000\Models\map;
use PetStore\V1000\Models\Order;
use PetStore\V1000\Apis\StoreApi;
    
/**
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 */
class StoreService implements StoreApi {
    /**
     * Returns pet inventories by status
     */
    public function getInventory() {
    }

    /**
     * Place an order for a pet
     */
    public function placeOrder(Order $body) {
    }

    /**
     * Find purchase order by ID
     */
    public function getOrderById($order_id) {
    }

    /**
     * Delete purchase order by ID
     */
    public function deleteOrder($order_id) {
    }
}
