<?php
/**
 *  Copyright 2015 Ye Wenbin
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
namespace PetStore\V1000\Models;

/**
 * The model Order.
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 */
class Order implements \ArrayAccess {
    /**
     * The id.
     * 
     * @Valid(type=integer)
     */
    public $id; /* int */

    /**
     * The pet_id.
     * 
     * @Valid(type=integer)
     */
    public $pet_id; /* int */

    /**
     * The quantity.
     * 
     * @Valid(type=integer)
     */
    public $quantity; /* int */

    /**
     * The ship_date.
     */
    public $ship_date; /* DateTime */

    /**
     * Order Status
     */
    public $status; /* string */

    /**
     * The complete.
     * 
     * @Valid(type=boolean)
     */
    public $complete; /* boolean */
    public function __construct(array $data = null) {
        if ($data === null) {
            return;
        }
        if (isset($data["id"])) {
            $this->id = $data["id"];
        }
        if (isset($data["pet_id"])) {
            $this->pet_id = $data["pet_id"];
        }
        if (isset($data["quantity"])) {
            $this->quantity = $data["quantity"];
        }
        if (isset($data["ship_date"])) {
            $this->ship_date = $data["ship_date"];
        }
        if (isset($data["status"])) {
            $this->status = $data["status"];
        }
        if (isset($data["complete"])) {
            $this->complete = $data["complete"];
        }
    }
  
    public function offsetExists($offset) {
         return isset($this->$offset);
    }
  
    public function offsetGet($offset) {
         return $this->$offset;
    }
  
    public function offsetSet($offset, $value) {
         $this->$offset = $value;
    }
  
    public function offsetUnset($offset) {
         unset($this->$offset);
    }
}
