<?php
/**
 *  Copyright 2015 Ye Wenbin
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
namespace PetStore\V1000\Models;

/**
 * The model User.
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 */
class User implements \ArrayAccess {
    /**
     * The id.
     * 
     * @Valid(type=integer)
     */
    public $id; /* int */

    /**
     * The username.
     */
    public $username; /* string */

    /**
     * The first_name.
     */
    public $first_name; /* string */

    /**
     * The last_name.
     */
    public $last_name; /* string */

    /**
     * The email.
     */
    public $email; /* string */

    /**
     * The password.
     */
    public $password; /* string */

    /**
     * The phone.
     */
    public $phone; /* string */

    /**
     * User Status
     * 
     * @Valid(type=integer)
     */
    public $user_status; /* int */

    public function __construct(array $data = null) {
        if ($data === null) {
            return;
        }
        if (isset($data["id"])) {
            $this->id = $data["id"];
        }
        if (isset($data["username"])) {
            $this->username = $data["username"];
        }
        if (isset($data["first_name"])) {
            $this->first_name = $data["first_name"];
        }
        if (isset($data["last_name"])) {
            $this->last_name = $data["last_name"];
        }
        if (isset($data["email"])) {
            $this->email = $data["email"];
        }
        if (isset($data["password"])) {
            $this->password = $data["password"];
        }
        if (isset($data["phone"])) {
            $this->phone = $data["phone"];
        }
        if (isset($data["user_status"])) {
            $this->user_status = $data["user_status"];
        }
    }
  
    public function offsetExists($offset) {
         return isset($this->$offset);
    }
  
    public function offsetGet($offset) {
         return $this->$offset;
    }
  
    public function offsetSet($offset, $value) {
         $this->$offset = $value;
    }
  
    public function offsetUnset($offset) {
         unset($this->$offset);
    }
}
