<?php
/**
 *  Copyright 2015 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
namespace PetStore\V1000\Apis;

use PetStore\V1000\Models\Pet;

/**
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 */
interface PetApi {
    /**
     * Update an existing pet
     */
    function updatePet(Pet $body);

    /**
     * Add a new pet to the store
     */
    function addPet(Pet $body);

    /**
     * Finds Pets by status
     */
    function findPetsByStatus($status);

    /**
     * Finds Pets by tags
     */
    function findPetsByTags($tags);

    /**
     * Find pet by ID
     */
    function getPetById($pet_id);

    /**
     * Updates a pet in the store with form data
     */
    function updatePetWithForm($pet_id, $name, $status);

    /**
     * Deletes a pet
     */
    function deletePet($api_key, $pet_id);

    /**
     * uploads an image
     */
    function uploadFile($pet_id, $additional_metadata, $file);
}
