<?php
/**
 *  Copyright 2015 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
namespace PetStore\V1000\Apis;

use PetStore\V1000\Models\User;

/**
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 */
interface UserApi {
    /**
     * Create user
     */
    function createUser(User $body);

    /**
     * Creates list of users with given input array
     */
    function createUsersWithArrayInput(array[User] $body);

    /**
     * Creates list of users with given input array
     */
    function createUsersWithListInput(array[User] $body);

    /**
     * Logs user into the system
     */
    function loginUser($username, $password);

    /**
     * Logs out current logged in user session
     */
    function logoutUser();

    /**
     * Get user by user name
     */
    function getUserByName($username);

    /**
     * Updated user
     */
    function updateUser($username, User $body);

    /**
     * Delete user
     */
    function deleteUser($username);
}
