<?php
/**
 *  Copyright 2015 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
namespace PetStore\V1000\Controllers;

use PetStore\V1000\Models\map;
use PetStore\V1000\Models\Order;
        
/**
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 * @RoutePrefix("/v2")
 */
class StoreController extends BaseController {
    /**
     * Returns pet inventories by status
     *
     * @GET("/store/inventory")
     */
    public function getInventory() {
        $this->storeService->getInventory();
    }

    /**
     * Place an order for a pet
     *
     * @POST("/store/order")
     */
    public function placeOrder() {
        $body = $this->objectConverter->convert($_POST, Order::CLASS);
        $this->storeService->placeOrder($body);
    }

    /**
     * Find purchase order by ID
     *
     * @GET("/store/order/{orderId}")
     */
    public function getOrderById($order_id) {
        $this->validator->validate([
            [
                'name' => 'order_id',
                'value' => $order_id,
                'required' => true
            ]
        ]);
        $this->storeService->getOrderById($order_id);
    }

    /**
     * Delete purchase order by ID
     *
     * @DELETE("/store/order/{orderId}")
     */
    public function deleteOrder($order_id) {
        $this->validator->validate([
            [
                'name' => 'order_id',
                'value' => $order_id,
                'required' => true
            ]
        ]);
        $this->storeService->deleteOrder($order_id);
    }
}
