<?php
/**
 *  Copyright 2015 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
namespace PetStore\V1000\Controllers;

use Phalcon\Mvc\Controller;
use PetStore\V1000\Models\User;

/**
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 */
class UserController extends Controller {
    /**
     * createUser
     *
     * Create user
     *
     */
     public function createUser($body) {
     }
    /**
     * createUsersWithArrayInput
     *
     * Creates list of users with given input array
     *
     */
     public function createUsersWithArrayInput($body) {
     }
    /**
     * createUsersWithListInput
     *
     * Creates list of users with given input array
     *
     */
     public function createUsersWithListInput($body) {
     }
    /**
     * loginUser
     *
     * Logs user into the system
     *
     */
     public function loginUser($username, $password) {
     }
    /**
     * logoutUser
     *
     * Logs out current logged in user session
     *
     */
     public function logoutUser() {
     }
    /**
     * getUserByName
     *
     * Get user by user name
     *
     */
     public function getUserByName($username) {
     }
    /**
     * updateUser
     *
     * Updated user
     *
     */
     public function updateUser($username, $body) {
     }
    /**
     * deleteUser
     *
     * Delete user
     *
     */
     public function deleteUser($username) {
     }

}
